import {test,expect} from '@playwright/test';
import {mockApprovedSession} from './approved-session.js';
import JSZip from 'jszip';
import {readFile} from 'node:fs/promises';
import {DOMParser} from '@xmldom/xmldom';

test('TOC shortcuts change one level at a time and share the parent picker hierarchy',async ({page}) => {
  const cloud=await mockApprovedSession(page);
  await page.goto('/',{waitUntil:'domcontentloaded'});
  await page.waitForFunction(() => window.epubMonacoEditor && document.querySelector('.ProseMirror'));
  await page.locator('.new-book').click();
  await page.locator('#title').fill('목차 단계 시험');
  const add = async title => { await page.locator('#add').click(); await page.locator('#ctitle').fill(title); };
  await add('A'); await add('B'); await add('C');
  const row = title => page.locator('#list .chapter').filter({hasText:title});
  await row('B').click({position:{x:55,y:15}});
  await page.locator('.parent-toc-button').click();
  await page.getByRole('option',{name:'A',exact:true}).click();
  await row('C').click({position:{x:55,y:15}});
  const depth = () => row('C').evaluate(element => Number(element.style.getPropertyValue('--toc-depth')));
  expect(await depth()).toBe(0);
  await page.keyboard.press('Shift+ArrowRight');
  await expect.poll(depth).toBe(1);
  await page.keyboard.press('Shift+ArrowRight');
  await expect.poll(depth).toBe(2);
  await page.locator('.draft-save').click();
  await expect(page.locator('.draft-save')).toBeEnabled();
  expect([...cloud.rows.values()][0].payload.chapters.find(chapter => chapter.title === 'C').level).toBe(3);
  await page.keyboard.press('Shift+ArrowLeft');
  await expect.poll(depth).toBe(1);
  await page.keyboard.press('Shift+ArrowLeft');
  await expect.poll(depth).toBe(0);
  await row('A').click({position:{x:55,y:15}});
  await page.locator('.parent-toc-button').click();
  await expect(page.getByRole('option',{name:'B',exact:true})).toHaveCount(0);
});

test('imported TOC edits update NAV and NCX while preserving anchors, paths, and spine',async ({page}) => {
  const zip = new JSZip();
  zip.file('mimetype','application/epub+zip');
  zip.file('META-INF/container.xml','<container xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OPS/package.opf" media-type="application/oebps-package+xml"/></rootfiles></container>');
  zip.file('OPS/package.opf','<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="id"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="id">toc-test</dc:identifier><dc:title>TOC</dc:title><dc:language>ko</dc:language></metadata><manifest><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/><item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/><item id="a" href="Text/a.xhtml" media-type="application/xhtml+xml"/><item id="b" href="Text/b.xhtml" media-type="application/xhtml+xml"/></manifest><spine toc="ncx"><itemref idref="a"/><itemref idref="b"/></spine></package>');
  zip.file('OPS/Text/a.xhtml','<html xmlns="http://www.w3.org/1999/xhtml"><head><title>A</title></head><body><p id="a">A</p></body></html>');
  zip.file('OPS/Text/b.xhtml','<html xmlns="http://www.w3.org/1999/xhtml"><head><title>B</title></head><body><p id="x">X</p><p id="y">Y</p></body></html>');
  zip.file('OPS/nav.xhtml','<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops"><head><title>TOC</title></head><body><nav epub:type="toc"><ol><li><a href="Text/a.xhtml#a">A</a></li><li><a href="Text/b.xhtml#x">B</a><ol><li><a href="Text/b.xhtml#y">B section</a></li></ol></li></ol></nav></body></html>');
  zip.file('OPS/toc.ncx','<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1"><head/><docTitle><text>TOC</text></docTitle><navMap><navPoint id="a" playOrder="1"><navLabel><text>A</text></navLabel><content src="Text/a.xhtml#a"/></navPoint><navPoint id="b" playOrder="2"><navLabel><text>B</text></navLabel><content src="Text/b.xhtml#x"/><navPoint id="b2" playOrder="3"><navLabel><text>B section</text></navLabel><content src="Text/b.xhtml#y"/></navPoint></navPoint></navMap></ncx>');
  await mockApprovedSession(page);
  await page.goto('/',{waitUntil:'domcontentloaded'});
  await page.waitForFunction(() => window.epubMonacoEditor && document.querySelector('.ProseMirror'));
  page.once('dialog',dialog => dialog.accept());
  await page.locator('input[type=file][accept^=".epub"]').setInputFiles({name:'toc.epub',mimeType:'application/epub+zip',buffer:await zip.generateAsync({type:'nodebuffer'})});
  await expect(page.locator('#status')).toContainText('불러왔');
  await page.locator('#list .chapter').filter({hasText:'B'}).click({position:{x:55,y:15}});
  await page.locator('#ctitle').fill('Changed B');
  await page.locator('.parent-toc-button').click();
  await page.getByRole('option',{name:'A',exact:true}).click();
  const download = page.waitForEvent('download'); await page.locator('#export').click();
  const output = await JSZip.loadAsync(await readFile(await (await download).path()));
  const parser = new DOMParser();
  const nav = parser.parseFromString(await output.file('OPS/nav.xhtml').async('string'),'application/xml');
  const links = [...nav.getElementsByTagName('a')];
  expect(links.map(link => link.getAttribute('href'))).toEqual(['Text/a.xhtml#a','Text/b.xhtml#x','Text/b.xhtml#y']);
  expect(links[1].textContent).toBe('Changed B');
  expect(links[1].parentNode.parentNode.parentNode).toBe(links[0].parentNode);
  const ncx = parser.parseFromString(await output.file('OPS/toc.ncx').async('string'),'application/xml');
  const points = [...ncx.getElementsByTagName('navPoint')];
  expect(points.map(point => point.getElementsByTagName('content')[0].getAttribute('src'))).toEqual(['Text/a.xhtml#a','Text/b.xhtml#x','Text/b.xhtml#y']);
  expect(points[1].getElementsByTagName('navLabel')[0].textContent).toBe('Changed B');
  expect(points[1].parentNode).toBe(points[0]);
  const opf = parser.parseFromString(await output.file('OPS/package.opf').async('string'),'application/xml');
  expect([...opf.getElementsByTagName('itemref')].map(item => item.getAttribute('idref'))).toEqual(['a','b']);
});
